# 1.2

In [1]:
from neo4j import GraphDatabase
from getpass import getpass

In [95]:
from neo4j import GraphDatabase

URI = "neo4j://127.0.0.1:7687"
USER = "neo4j"
# PW = getpass("Masukkan password Neo4j: ")
PW = "24031554098"
DB = "uts"

driver = GraphDatabase.driver(URI, auth=(USER, PW))
driver.verify_connectivity()

print("Koneksi berhasil!")

Koneksi berhasil!

In [51]:
with driver.session(database=DB) as session:
    result = session.run("RETURN 1 AS tes")
    print(result.single()["tes"])

1

In [45]:
# 1.2.3 pembuatan sebuah Node berikut dengan relationship-nya.
def add_friends(driver,name,friends):
    with driver.session(database=DB) as session:
        session.run(
            "MERGE (n:Person {name: $name}) "
            "MERGE (f:Person {name: $friends}) "
            "MERGE (n)-[:KNOWS]->(f) ",
            name=name,friends=friends
        ).consume()
    print(f"Relasi {name} -> {friends} berhasil dibuat.")

In [46]:
# 1.2.4 mencetak dan menjalankan keseluruhan
def print_friends(driver, name):
    with driver.session(database=DB) as session:
        result= session.run(
            "MATCH (n:Person)-[:KNOWS]->(f) "
            "WHERE n.name = $name "
            "RETURN f.name as friends " 
            "ORDER BY friends",
            name=name
        )
        records = result
        print(f"daftra teman {name} :")
        for record in records:
            print(f'- {record["friends"]}')

In [47]:

with GraphDatabase.driver(URI,auth=auth, ) as driver:
    add_friends(driver,"Arthur", "Guinevere")
    add_friends(driver,"Arthur", "Lancelot")
    add_friends(driver,"Arthur", "Merlin")
    print_friends(driver, "Arthur")

Relasi Arthur -> Guinevere berhasil dibuat.
Relasi Arthur -> Lancelot berhasil dibuat.
Relasi Arthur -> Merlin berhasil dibuat.
daftra teman Arthur :
- Guinevere
- Lancelot
- Merlin

In [48]:
# jawaban tugas
with open("jawaban.txt", "r", encoding="utf-8") as file:
    jawaban = file.read()

print(jawaban)

1.
soal : apa nama database yang digunakan pada tutorial ini
jawab : DB = "uts"

2.
soal : sebutkan akses lain (seperti sintaks DDL/DML CYPHER) yang dapat digunakan untuk mengakses database lain dalam 1 instance
jawab :
# untuk melihat daftar database (SHOW DATABASES;)
# contoh
SHOW DATABASES;

# memilih database yang akan digunakan (USE [nama_database])
# contoh
USE uts
RETURN 'Berhasil menggunakan database uts' AS pesan;

# melihat jumlah node di database terpilih
(USE [nama_database] MATCH (n) RETURN COUNT(n) as jumlah_node;)
# contoh
USE uts
MATCH (n)
RETURN COUNT(n) as jumlah_node;

# membuat database baru (CREATE DATABASE [nama_database])
# contoh
CREATE DATABASE test2;

# pindah ke database lain (USE[nama_database])
# contoh
USE test
RETURN 'Berhasil menggunakan database test' AS pesan;

# melihat node di database baru (USE [nama_database] MATCH (n) RETURN COUNT(n) as jumlah_node;)
# contoh
USE test
MATCH (n)
RETURN COUNT(n) as jumlah_node;

# hapus database (DROP DATABASE [nama_database])
DROP DATABASE test;

3.
soal : apa jenis graf yang telah dibuat disini
jawab : Graf berarah, karena pakai tanda panah (->) (directed graph),bukti = (n)-[:KNOWS]->(f) ,artinya n mengenal f

In [52]:
with driver.session(database=DB) as session:
    session.run(
        "MATCH (n) "
        "DETACH DELETE n"
    ).consume()

print("berhasil hapus.")

berhasil hapus.

# 1.3

In [84]:
import zipfile
import os
import pandas as pd
import glob
import shutil
from tqdm.auto import tqdm
import argparse as ap
import sys

## 1.3.1

In [54]:
zip_path = r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce-dataset.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    for nama_file in zip_ref.namelist():
        print(nama_file)

category_tree.csv
events.csv
item_properties_part1.csv
item_properties_part2.csv

In [56]:


# Folder tujuan ekstraksi
extract_folder = r"D:\coding\coding semester 5\graf sains data\UTS"

# Buat folder tujuan jika belum ada
os.makedirs(extract_folder, exist_ok=True)

# Ekstrak semua file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_folder)

print("Ekstraksi berhasil!")
print("Lokasi folder:", extract_folder)

# Tampilkan daftar file hasil ekstraksi
for nama_file in os.listdir(extract_folder):
    print(nama_file)

Ekstraksi berhasil!
Lokasi folder: D:\coding\coding semester 5\graf sains data\UTS
26_UTS-GSD.pdf
category_tree.csv
ecommerce-dataset.zip
events.csv
item_properties_part1.csv
item_properties_part2.csv
jawaban.txt
main.ipynb
main.py
myvenv
requirements.txt
uts.cypher

In [57]:
os.remove(r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce-dataset.zip")

In [59]:
folder = r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset"
os.makedirs(folder, exist_ok=True)
folder_asal = r"D:\coding\coding semester 5\graf sains data\UTS"
folder_tujuan = os.path.join(folder_asal, "ecomers dataset")

os.makedirs(folder_tujuan, exist_ok=True)

file_data = (
    glob.glob(os.path.join(folder_asal, "*.csv")))

for file in file_data:
    shutil.move(file, folder_tujuan)

print("File berhasil dipindahkan.")

File berhasil dipindahkan.

In [61]:
import pandas as pd

# 1. Baca category_tree.csv
df_category = pd.read_csv(
    r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\category_tree.csv"
)

# 2. Baca events.csv
df_events = pd.read_csv(
    r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\events.csv"
)

# 3. Baca item_properties_part1.csv
df_item_properties1 = pd.read_csv(
    r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\item_properties_part1.csv"
)

# 4. Baca item_properties_part2.csv
df_item_properties2 = pd.read_csv(
    r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\item_properties_part2.csv"
)

# Tampilkan setiap DataFrame
print("======= category_tree.csv ===========")
display(df_category)
print()
print("======= events.csv ===========")
display(df_events)
print()
print("======= item_properties_part1 ===========")
display(df_item_properties1)
print()
print("======= item_properties_part2 ===========")
display(df_item_properties2)
print()

======= category_tree.csv ===========

      categoryid  parentid
0           1016     213.0
1            809     169.0
2            570       9.0
3           1691     885.0
4            536    1691.0
...          ...       ...
1664          49    1125.0
1665        1112     630.0
1666        1336     745.0
1667         689     207.0
1668         761     395.0

[1669 rows x 2 columns]

======= events.csv ===========

             timestamp  visitorid event  itemid  transactionid
0        1433221332117     257597  view  355908            NaN
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756101 rows x 5 columns]

======= item_properties_part1 ===========

              timestamp  itemid    property                            value
0         1435460400000  460429  categoryid                             1338
1         1441508400000  206783         888          1116713 960601 n277.200
2         1439089200000  395014         400  n552.000 639502 n720.000 424566
3         1431226800000   59481         790                       n15360.000
4         1431831600000  156781         917                           828513
...                 ...     ...         ...                              ...
10999994  1439694000000   86599  categoryid                              618
10999995  1435460400000  153032        1066                 n1020.000 424566
10999996  1440298800000  421788         888               35975 856003 37346
10999997  1437879600000  159792         400  n552.000 639502 n720.000 424566
10999998  1436065200000  464846         790                      n410640.000

[10999999 rows x 4 columns]

======= item_properties_part2 ===========

             timestamp  itemid property                             value
0        1433041200000  183478      561                            769062
1        1439694000000  132256      976                   n26.400 1135780
2        1435460400000  420307      921                   1149317 1257525
3        1431831600000  403324      917                           1204143
4        1435460400000  230701      521                            769062
...                ...     ...      ...                               ...
9275898  1433646000000  236931      929                           n12.000
9275899  1440903600000  455746        6                     150169 639134
9275900  1439694000000  347565      686                            610834
9275901  1433646000000  287231      867                            769062
9275902  1442113200000  275768      888  888666 n10800.000 746840 1318567

[9275903 rows x 4 columns]

## 1.3.2

README
Perhatikan fitur yang telah diunduh dengan rincian sebagai berikut:
1. timestamp: Waktu dalam format unix epoch.
2. visitorid: ID unik pengunjung.
3. event: Jenis interaksi default: view, addtocart, transaction. (d) itemid: ID unik produk.
4. transactionid: ID transaksi, hanya terisi saat event berjenis ’transaction’.

In [72]:
df_list = [
    ("df_category", df_category),
    ("df_events", df_events),
    ("df_item_properties1", df_item_properties1),
    ("df_item_properties2", df_item_properties2)
]

for nama,df in df_list:
    print(f"==========={nama}==========")
    print(f"UKURAN DATASET : {df.shape}")
    df.info()
    display(df.isnull().sum())
    print()

===========df_category==========
UKURAN DATASET : (1669, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1669 entries, 0 to 1668
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   categoryid  1669 non-null   int64
 1   parentid    1644 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 26.2 KB

categoryid     0
parentid      25
dtype: int64

===========df_events==========
UKURAN DATASET : (2756101, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2756101 entries, 0 to 2756100
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      int64
 1   visitorid      int64
 2   event          object
 3   itemid         int64
 4   transactionid  float64
dtypes: float64(1), int64(3), object(1)
memory usage: 105.1+ MB

timestamp              0
visitorid              0
event                  0
itemid                 0
transactionid    2733644
dtype: int64

===========df_item_properties1==========
UKURAN DATASET : (10999999, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999999 entries, 0 to 10999998
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  int64
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: int64(2), object(2)
memory usage: 335.7+ MB

timestamp    0
itemid       0
property     0
value        0
dtype: int64

===========df_item_properties2==========
UKURAN DATASET : (9275903, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9275903 entries, 0 to 9275902
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  int64
 1   itemid     int64
 2   property   object
 3   value      object
dtypes: int64(2), object(2)
memory usage: 283.1+ MB

timestamp    0
itemid       0
property     0
value        0
dtype: int64

## 1.3.3 - 1.3.5

In [ ]:
# 1.3.3
def parse_arguments():
    parser = ap.ArgumentParser(
        description="import RetailRocket (events.csv) ke database uts"
    )
    
    parser.add_argument(
         "-u",
         "--user",
         default="neo4j",
         help="username Neo4j"
     )
    parser.add_argument(
        "-p",
        "--password",
        default="",
        help="password Neo4j"
    )
    
    parser.add_argument(
        "-b",
        "--bolt",
        default="neo4j://127.0.0.1:7687",
        help="URI conected Neo4j"
    )
    
    parser.add_argument(
       "-d",
       "--database",
       default="uts",
       help="Nama database Neo4j" 
    )
    
    parser.add_argument(
        "-s",
        "--source",
        default=r"D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset",
        help="folder dataset"
    )
    return parser.parse_args(args=[])

args = parse_arguments()
print("Username:", args.user)
print("URI:", args.bolt)
print("Database:", args.database)
print("Folder dataset:", args.source)

Username: neo4j
URI: neo4j://127.0.0.1:7687
Database: uts
Folder dataset: D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset

In [90]:
csv_file_path = os.path.join(args.source,"events.csv")
if not os.path.exists(csv_file_path):
    print(f"Error: File '{csv_file_path}' tidak ditemukan")
    sys.exit(1)
try:
    driver = GraphDatabase.driver(
        args.bolt,auth=(args.user, PW)
    )
    driver.verify_connectivity()
    
except Exception as e:
    print(f"gagal terhubung ke database: {e}")
    sys.exit(1)

print(f"File ditemukan: {csv_file_path}")
print("Koneksi Neo4j berhasil!")

File ditemukan: D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\events.csv
Koneksi Neo4j berhasil!

In [92]:
# 1.3.3 - Fungsi untuk impor data RetailRocket

def create_constraints(session):
    session.run("""
        CREATE CONSTRAINT visitor_id_unique IF NOT EXISTS
        FOR (v:Visitor)
        REQUIRE v.visitorId IS UNIQUE
    """)

    session.run("""
        CREATE CONSTRAINT item_id_unique IF NOT EXISTS
        FOR (i:Item)
        REQUIRE i.itemId IS UNIQUE
    """)

    print("Constraint berhasil dibuat!")


def import_batch(tx, batch):
    query = """
    UNWIND $batch AS row

    MERGE (v:Visitor {visitorId: row.visitorid})
    MERGE (i:Item {itemId: row.itemid})

    WITH v, i, row
    CALL {
        WITH v, i, row
        WITH v, i, row WHERE row.event = 'view'
        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)

        UNION ALL

        WITH v, i, row
        WITH v, i, row WHERE row.event = 'addtocart'
        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)

        UNION ALL

        WITH v, i, row
        WITH v, i, row WHERE row.event = 'transaction'
        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)
    }
    """

    tx.run(query, batch=batch)

In [93]:

# 1.3.4
batch_size = 10000
with driver.session(database=args.database) as session:
    create_constraints(session)
    print(f"membaca file dari: {csv_file_path}")
    
    chunks = pd.read_csv(csv_file_path, chunksize=batch_size)
    
    total_row = sum(1 for _ in open(csv_file_path, encoding="utf-8")) - 1
    total_chunks = (total_row// batch_size) + 1
    
    print("Memulai proses impor data ke Neo4j...")
    for chunk in tqdm(
        chunks, total=total_chunks,desc="mengimpor bach data"
    ):
        chunk["transactionid"] = (
            chunk["transactionid"].fillna("").astype(str)
        )
        records = chunk.to_dict(orient="records")
        session.execute_write(import_batch,records)
driver.close()
print("import berhasil")

Constraint berhasil dibuat!
membaca file dari: D:\coding\coding semester 5\graf sains data\UTS\ecommerce dataset\events.csv
Memulai proses impor data ke Neo4j...

mengimpor bach data:   0%|          | 0/276 [00:00<?, ?it/s]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   0%|          | 1/276 [00:11<52:58, 11.56s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   1%|          | 2/276 [00:14<29:09,  6.38s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   1%|          | 3/276 [00:16<20:08,  4.43s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   1%|▏         | 4/276 [00:17<14:56,  3.30s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   2%|▏         | 5/276 [00:19<12:01,  2.66s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   2%|▏         | 6/276 [00:21<11:16,  2.51s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   3%|▎         | 7/276 [00:23<09:57,  2.22s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   3%|▎         | 8/276 [00:24<08:34,  1.92s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   3%|▎         | 9/276 [00:25<07:29,  1.68s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   4%|▎         | 10/276 [00:27<07:07,  1.61s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   4%|▍         | 11/276 [00:28<06:55,  1.57s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   4%|▍         | 12/276 [00:29<06:30,  1.48s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "
mengimpor bach data:   5%|▍         | 13/276 [00:31<05:58,  1.36s/it]Received notification from DBMS server: <GqlStatusObject gql_status='01N00', status_description='warn: feature deprecated. CALL subquery without a variable scope clause is deprecated. Use CALL (v, i, row) { ... }', position=<SummaryInputPosition line=8, column=5, offset=140>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 140, 'line': 8, 'column': 5}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n    UNWIND $batch AS row\n\n    MERGE (v:Visitor {visitorId: row.visitorid})\n    MERGE (i:Item {itemId: row.itemid})\n\n    WITH v, i, row\n    CALL {\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'view'\n        CREATE (v)-[:VIEWED {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'addtocart'\n        CREATE (v)-[:ADDED_TO_CART {timestamp: row.timestamp}]->(i)\n\n        UNION ALL\n\n        WITH v, i, row\n        WITH v, i, row WHERE row.event = 'transaction'\n        CREATE (v)-[:BOUGHT {timestamp: row.timestamp,transactionId: row.transactionid}]->(i)\n    }\n    "

import berhasil

In [96]:
with driver.session(database=DB) as session:
    result = session.run("""
        MATCH (v:Visitor)
        WITH count(v) AS totalVisitor
        MATCH (i:Item)
        WITH totalVisitor, count(i) AS totalItem
        MATCH ()-[r]->()
        RETURN
            totalVisitor,
            totalItem,
            count(r) AS totalRelationship
    """)

    data = result.single()

    print("Jumlah Visitor:", data["totalVisitor"])
    print("Jumlah Item:", data["totalItem"])
    print("Jumlah Relationship:", data["totalRelationship"])

Jumlah Visitor: 1407580
Jumlah Item: 235061
Jumlah Relationship: 2756101